### ISSUE TITLE
Change to src/pck_name layout

### ISSUE THREAD

**Issue by michaelaye** [planetarypy/package-template#1]
I'd like to change this to the now recommended src/pck_name layout.

The Python packaging authority has changed to that layout as well:

https://github.com/pypa/sampleproject

and it solves several outer potential pitfalls concerning tox and pytest (testing the installed vs the local package).

So, I think we should spread the recommended layout via our template.
Any objections?

**Comment by rbeyer** [comment]
I want to make sure I'm understanding this correctly: this proposed layout just inserts a directory named 'src/' in the main repo that only contains a single directory that is the package name?

For example, before you might have the `pvl` repo, the Python library was in a `pvl/` directory in that repo, and under this new layout you'd have a `src/pvl/` directory?

At first blush, this seems obfuscating.  I tried doing a little research, and this seems 'fresh.'  The change to the sample project just got merged three months ago, but the text in the Python Packaging Guide still recommends "a single top-level package that has the same name as your project."  I'm not against making this change, it just seems unnecessary to me at this point in our template.  Individual package authors can make that choice, but it seems to me that the package-template should be the most generic and follow the Packaging Guide.  If this change goes through and it gets updated, and becomes common practice, we can always change it.

Maybe you can make a better case for why this is needed for us right now?

I've never had any problems with tox testing with the current situation.  And simply having a development environment for your package that does NOT have the existing package installed alleviates any problems you'd have with pytest testing the installed package instead of the local, as far as I can tell, but again, maybe I'm missing something fundamental here.

**Comment by michaelaye** [comment]
Not sure I can make a stronger case than the official example project that everybody "should" use to design a new project.

But here's some links with more details of the things that can go wrong:
https://blog.ionelmc.ro/2014/05/25/python-packaging/#the-structure

This change is being discussed for several years now, and after PyCon2019 the PyPA organization finally listened to the many package maintainers' reports on error cases.
I myself haven't run into much trouble with this myself, but that's most probably b/c I'm not a tox user? Also, I wouldn't have cluttered scripts in my root, suddenly being on the path.
But as it looks like this becomes/is the new standard, I think we should follow it.

Also look at pytest's recommendation regarding having test names being the same as the function names, which would be possible using the src layout:
https://docs.pytest.org/en/latest/goodpractices.html#tests-outside-application-code

**Comment by rbeyer** [comment]
Hm.  My point is that while the GitHub repo for the sample project now has that layout, there is not yet documentation in the Packaging Guide that recommends this, it still recommends the older practice.  So just as we are not writing PlanetaryPy to the latest version of Python, but a more stable version, we should do the same for our template, for now.  Maybe all of that documentation will get sorted out in the next year, and then I'd have no reservations about switching, or maybe we'll run into roadblocks, and that will become the logical conclusion.

I don't read that section you linked as pytest recommending a src layout.  It says "If you need to have test modules with the same name ..." then having a src layout facilitates that, so that's an 'if / then' kind of recommendation, not a 'do this all the time' kind of thing, as I read it.

What do other folks think?

**Comment by AndrewAnnex** [comment]
ehh, I've seen this question before regarding pytest/tox but I also haven't run into those issues with spiceypy (yet iirc). I think it is fine to adopt it, but more so because it isn't that critical of choice to make, this is just a template after all.

**Comment by michaelaye** [comment]
I would bet an arm and a leg that the sample project is used more often than the documentation to guide somebody’s layout. Who doesn’t develop from example code? 

The other argument is that with restricted manpower I’d like to prevent as many obvious future changes as possible to save on tasks. In the same vein (vane? Vain?) I’d like to remove setup.py but maybe I keep that for the PlanetaryPy package itself and not for the template although the differences could be questioned, obviously.

**Comment by michaelaye** [comment]
fixed by #5 and #6
